apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-shared
spec:
  template:
    spec:
      containers:
        - name: test
          env:
            - name: DUMMY2
              value: "dummy-val2"