apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml

patches:

  - patch: |-
      - op: add
        path: /metadata/labels/dummy
        value: "test"
    target: {} # All resources

